### ISSUE TITLE
signin_path and signup_path

### ISSUE THREAD

**Issue by frabrunelle** [dailycred/dailycred#7]
Right now, login_path generates a link that redirects to the Email Sign Up page. It would be nice if it was also possible to generate a link that redirects to the Email Sign In page because I have a "Sign in" link on my site and users expect to see a Email Sign In page when they click on it (although it's possible to toggle the form so that it becomes a Email Sign In page, it saves one click if the form is already a Email Sign In page).

I would suggest renaming login_path to signup_path and naming the path for the Email Sign In page signin_path.

Thanks!

**Comment by hstove** [comment]
Hey there!

I agree that the naming is confusing. In the meantime, you can send your users to the 'email sign in' page by passing `action=signin` in your omniauth request.

``` Ruby
= link_to "Sign In", login_path(action: "signin")
= link_to "Sign Up", login_path
```

**Comment by frabrunelle** [comment]
That works, thank you :+1:
