### ISSUE TITLE
Is this gem usable with Sinatra?

### ISSUE THREAD

**Issue by retorquere** [dailycred/dailycred#9]
The documentation leans heavily towards rails use, but since it uses omniauth, I'm guessing/hoping it will work similarly to the auth0 ruby gem for omniauth (which was easy enough to use with Sinatra).

**Comment by hstove** [comment]
The `dailycred` gem in particular is mostly Rails helpers, so you wouldn't get much use out of it. With Sinatra, I'd recommend just using the [dailycred-omniauth](https://github.com/dailycred/omniauth_dailycred) gem, which provides only the omniauth plugin. Hope that helps!
